In [1]:
my_list=[1,2,3]

In [2]:
import numpy as np

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
arr=np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
### if i want even numbers , i add 2
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [11]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [12]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [13]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [14]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [15]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [16]:
np.random.rand(5)

array([ 0.89305285,  0.10494732,  0.8141238 ,  0.11082671,  0.54816602])

In [17]:
np.random.rand(5,5)

array([[ 0.62372654,  0.58337962,  0.28672292,  0.76210353,  0.78521896],
       [ 0.28724182,  0.2192973 ,  0.10331495,  0.8364909 ,  0.44551039],
       [ 0.08400526,  0.28995518,  0.56008457,  0.67123777,  0.67046383],
       [ 0.08945041,  0.09253516,  0.93645416,  0.84135304,  0.11550553],
       [ 0.55798268,  0.34543289,  0.8380254 ,  0.76808004,  0.96906257]])

In [18]:
np.random.randn(2)

array([-0.524796  , -0.18978537])

In [19]:
np.random.randn(4,4)

array([[ 0.59601916,  1.83811291,  0.15515972,  1.09157493],
       [ 0.48109396,  1.30394453,  0.73419655, -0.20962366],
       [ 0.32349826,  2.51045364,  1.6571281 ,  0.43678908],
       [-0.54284631, -0.57931088, -0.21222868,  1.68829748]])

In [20]:
np.random.randint(1,100)

49

In [21]:
np.random.randint(1,100,10)

array([43, 38, 43, 99, 25, 10, 27, 14, 47, 36])

In [22]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

# Indexing and Selection

In [23]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
arr_2d [ 1:,:2]

array([[20, 25],
       [35, 40]])

In [25]:
#######

In [26]:
arr_2d=np.arange(50).reshape(5,10)

In [27]:
#### GRAB!! 23,24,33,34
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [28]:
arr_2d[2:4, 3:5]

array([[23, 24],
       [33, 34]])

In [29]:
##### GRAB!! 26,27,36,37  
arr_2d[2:4,6:8]

array([[26, 27],
       [36, 37]])

# NumPy Operations

In [30]:
import numpy as np 

In [31]:
arr = np.arange(0,11)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [34]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [36]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [37]:
arr/arr

C:\Users\kozyr\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [38]:
1/arr

C:\Users\kozyr\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [39]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [40]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

# Exercise 

In [41]:
arr = np.arange(1,11)

In [42]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [44]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [45]:
np.ones(10)*5

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [46]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [47]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [48]:
mat=[[0,1,2],[3,4,5],[6,7,8]]

In [49]:
np.array(mat)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
#### or 
np.arange(9) .reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [52]:
np.random.rand(1)

array([ 0.35298945])

In [53]:
np.random.randn(25)

array([-0.25419476, -0.86104844,  0.27188594, -0.68024297,  0.39842803,
       -0.90379944, -1.16740198,  0.93533888, -0.14808291,  0.05445523,
       -0.60158169,  1.0754513 , -0.3535996 , -0.9125542 , -1.69148544,
        0.2482347 ,  0.90389361,  0.23585209,  1.60095258, -0.45705022,
        0.32946649,  1.29761069,  0.5134501 ,  0.4935758 ,  1.9812962 ])

In [54]:
np.arange(1,101) .reshape(10,10)/100

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [55]:
##### or

np.linspace(0.01,1,100) .reshape(10,10)

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [56]:
np.linspace(0,1,20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

In [57]:
mat = np.arange(1,26).reshape(5,5)


In [58]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [59]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [60]:
mat[3,4]

20

In [61]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [62]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [63]:
mat[4:,0:]

array([[21, 22, 23, 24, 25]])

In [64]:
mat[3:,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [65]:
np.sum(mat)

325

In [66]:
np.std(mat)

7.2111025509279782

In [67]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

### Training time 

In [68]:
np.random.randn(5,5) .reshape(5,5)

array([[ 0.04452478, -1.08481451,  0.17653473,  0.79548866,  0.52155367],
       [-0.3158423 ,  1.02268803,  0.66813569, -0.40384425,  1.54725741],
       [ 0.56363526, -0.67764922,  2.1222567 , -1.19927255, -1.24696382],
       [-1.17612752, -0.45988806, -1.07551922,  0.24887244,  0.99072641],
       [-1.34084881, -0.49888751, -1.11084308,  1.53132042,  0.56491888]])

In [69]:
mat=np.arange(100) .reshape(10,10) 

In [70]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [71]:
### index 43 to 76 then 65
mat[4:8,3:7][2:3,2:3]

array([[65]])